spring:
  application:
    name: arbiter
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        http.server.requests: true
