spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations:
      - classpath:db/migration
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,metrics

arbiter:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    com.ilovepawn.arbiter: DEBUG
