spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/arbiter?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: arbiter
    password: arbiterpw
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: arbiter
    password: arbiterpw

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
    com.ilovepawn.arbiter: DEBUG
